### ISSUE TITLE
Campos Fone e Fax do Registro 0100

### ISSUE THREAD

**Issue by djeisonselzlein** [jean-merelis/coffeepot-br-sped-fiscal#15]
Olá @jean-merelis 
Recebemos solicitação de que os campos 11 (Fone) e 12 (Fax) do Registro 0100 (Contabilista) sejam gerados com valor vazio quando não houver informação. Gostaria de ver contigo se você teria alguma objeção quanto a alteração deste registro. Verifiquei que na configuração deste Field está explícito que seja gerada a string vazia quando não houver valor.

**Comment by jean-merelis** [comment]
@djeisonselzlein Realmente estes campos não devem ser preenchidos se forem `null` ou `empty`. Com certeza foi uma falha no mapeamento. Pode alterar sim.

**Comment by djeisonselzlein** [comment]
#16

**Comment by djeisonselzlein** [comment]
Ok, submeti a alteração na PR #16 =)
