### ISSUE TITLE
Alterar projeto para utilizar a API de datas do pacote java.time. Alguém tem alguma objeção?

### ISSUE THREAD

**Issue by jean-merelis** [jean-merelis/coffeepot-br-sped-fiscal#20]

**Comment by djeisonselzlein** [comment]
Nenhuma objeção. Sou a favor e posso ajudar se necessário.

**Comment by jean-merelis** [comment]
Ótimo. Devo começar na próxima semana, qualquer coisa entro em contato.
Obrigado.

**Comment by selzlein** [comment]
Olá @jean-merelis, teve alguma novidade por aqui? Posso ajudar nesse processo, se quiser.

**Comment by jean-merelis** [comment]
Olá @selzlein . Ainda não comecei. Estou envolvido em um projeto que está me tomando bastante tempo. Se tu quiser e tiver disponibilidade pra fazer as alterações, sinta-se a vontade em fazê-las, pois eu devo demorar algumas semanas ainda para fazer estas alterações. Se precisar de algum auxilio, é só dar um toque que tentarei te ajudar o máximo que eu puder.

**Comment by jean-merelis** [comment]
Comecei a fazer as alterações.

**Comment by selzlein** [comment]
Ok, acabei não conseguindo começar... quando puder entro em contato novamente.
