### ISSUE TITLE
Versão '1.0.0-Beta.15' no Maven

### ISSUE THREAD

**Issue by nielsonjr** [jean-merelis/coffeepot-br-sped-fiscal#40]
Olá, há a possibilidade de disponibilizar a versão atual de desenvolvimento ('1.0.0-Beta.15') no Maven? Estou dependendo das entidades modificadas nesta versão.

Agradeço desde já.

**Comment by jean-merelis** [comment]
@nielsonjr desculpe a demora. Acabei de publicar. Se tiver algum problema, deixe-me saber.
