### ISSUE TITLE
Make it available on Maven Repository or Central

### ISSUE THREAD

**Issue by djeisonselzlein** [jean-merelis/coffeepot-br-sped-fiscal#5]
Hi there,

I would like to know if you could make this project available as a maven dependency on Maven Repository.

Best regards,
Djeison A. Selzlein

**Comment by djeisonselzlein** [comment]
Desculpe, só agora vi que este repositório é brasileiro.
Poderia disponibilizar este projeto como artefato no Maven Repository?

**Comment by jean-merelis** [comment]
Olá Djeison. Desculpe a demora, é que esta semana está bem corrida. 
Este projeto ainda precisa implementar alguns mapeamentos para alguns registros do SPED, mas se já for útil para tu, posso tornar a versão para beta.0 e subir para o Maven Central.
Farei isto amanhã a tarde.

**Comment by djeisonselzlein** [comment]
Tudo bem. Agradeço se puder fazer isso.
Grato :D

**Comment by djeisonselzlein** [comment]
Precisei de algumas alterações no Enum VersaoLayout, devido a nova versão 1.11 do SPED. Ainda preciso verificar as alterações na geração do arquivo para validar nesta nova versão. Para isso fiz fork do seu projeto e estou trabalhando nisso. Caso tenha interesse em agregar neste projeto, posso criar PRs.

**Comment by jean-merelis** [comment]
Seria ótimo contar com a sua colaboração. 
Vi em teu repositório que tu está usando o Lombok, para mim está OK, também o uso em meus projetos.
Vou esperar teu PR para eu subir para o Maven.

**Comment by djeisonselzlein** [comment]
Ok, criei o PR. Grato :D

**Comment by jean-merelis** [comment]
Feito. Qualquer coisa, sinta-se a vontade em abrir uma nova _issue_.
Obrigado pela colaboração.
