### ISSUE TITLE
Refatoramento no enum DocumentoFiscal

### ISSUE THREAD

**Issue by jean-merelis** [jean-merelis/coffeepot-br-sped-fiscal#9]
@djeisonselzlein Estou pensando em fazer um refatoramento no enum DocumentoFiscal. O refatoramento é para reduzir o nome do enum e seguira a seguinte sistemática: letra M (modelo) + o código do modelo fiscal. Desta forma **DocumentoFiscal.NOTA_FISCAL** passaria a ser **DocumentoFiscal.M01**, **DocumentoFiscal.NOTA_FISCAL_AVULSA** para **DocumentoFiscal.M1B** e assim por diante.

_Esta refatoração seria para um alinhamento com um projeto interno que tenho aqui._

A questão é, qual seria o impacto no projeto de vocês? Alguma objeção?

**Comment by djeisonselzlein** [comment]
Boa tarde @jean-merelis analisamos a nossa implementação e não temos objeção quanto a mudança.
Por favor, fique a vontade para alterar. Agradecemos a preocupação.
